<?php

namespace AppBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStudents()
    {
        $this->getEntityManager()->getConnection()->getConfiguration()->setSQLLogger(null);
        $queryBuilder = $this->getEntityManager()->getRepository('AppBundle:Student')->createQueryBuilder('a');

        return $queryBuilder->getQuery()->getResult();
    }

}
